server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.pk.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profile: user
  application:
    name: WoniuShopCloud-Provider-User-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.7.197:3306/shop
    username: root
    password: pk187287
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:7001/eureka
  instance: 
    instance-id: provider-user-8001 
    prefer-ip-address: true  
info: 
  app.name: WoniuShopCloud
  auther: pk
  bulid.artifactId: ${project.artifactId}$
  bulid.version: ${project.version}$